# Generated by Django 4.2.2 on 2023-06-20 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_registrationdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationdetails',
            name='lastname',
        ),
        migrations.AddField(
            model_name='registrationdetails',
            name='password',
            field=models.CharField(default=' ', max_length=12),
            preserve_default=False,
        ),
    ]
