# Generated by Django 4.2.2 on 2023-06-20 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_remove_registrationdetails_lastname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationdetails',
            name='email',
            field=models.EmailField(default=' ', max_length=254),
            preserve_default=False,
        ),
    ]
